### ISSUE TITLE
Editor shortcuts (s,v,e) do not work when the styles pane is in focus

### ISSUE THREAD

**Issue by nmaehlmann** [tikzit/tikzit#105]
Steps to reproduce:
1. Place a vertex.
2. Choose an edge style.
3. Press "e" (nothing happens).
4. Try to add the edge and end up placing an unwanted vertex in your graphic.

Version: 2.1.6
Platform: Windows 10

**Comment by 0xACE** [comment]
I guess that happens because the style pane is taking focus so you can "search" for items in the style pane. For example hitting `d` takes me to styles starting with the letter `d`. In your case it's trying to look for `e` rather than selecting the tool `e`

Anyhow. I recommend you only use the `select` (`s`) tool as it automatically guesses if it should create a `vertex` or `edge` depending on what your mouse is on top off. (Though in my experience the select tool has a tendency to miss or create 2 edges, but it may be my mouse and me using bad hardware...)

I'd say this isn't a issue per se and that you could close this issue.

**Comment by nmaehlmann** [comment]
Thank you for the hint. I will continue to use the select tool with right click from now on.
