### ISSUE TITLE
Creating new node styles 

### ISSUE THREAD

**Issue by AravindaSakshi** [tikzit/tikzit#116]
Hi All --- 

Is there a way to create new node styles like triangles and other pictures. Especially I need tilted /cut pictures used for process and states in "picturing the quantum process book". Any help?? 

Thanking you 

Aravinda

**Comment by 0xACE** [comment]
Afaik, there isn't without copy/pasting etc...

Though a draft on what you want to achieve might lead to some suggestions...

**Comment by AravindaSakshi** [comment]
Thanks --- I was able to achieve  through copy/pasting .... 

How to increase the thickness of edeges??

**Comment by akissinger** [comment]
Hi Aravinda. There's no full style file for Picturing Quantum Processes, since it was made using an older version of tikzit using a more manual/hacked together process. However, I made a template some time ago showing how to make differently shaped nodes using a combination of tikzstyles/tikzdefs. You can essentially do anything with tikzit that is possible using the PGF/tikz library (e.g. defining new node shapes, making nodes and edges bold, etc), but not all things show up in the tikzit GUI, so you may need to preview the diagram to see the shapes. See attached for some examples.

[tikzpaper.zip](https://github.com/tikzit/tikzit/files/6384033/tikzpaper.zip)

**Comment by AravindaSakshi** [comment]
Thank you very much Aleks --
