### ISSUE TITLE
Linux compilation make file

### ISSUE THREAD

**Issue by hildogjr** [tikzit/tikzit#18]
Please include the make file or a Linux compilation step-by-step tutorial.
This will help the users to install and programmers to help fix issues.

**Comment by akissinger** [comment]
You need to have Qt installed and run qmake to get a makefile. This is explained in README.md.

**Comment by hildogjr** [comment]
Thanks @iblech, I am using Ubuntu 16 / 18, `flex` and `bison` are not default available. I did `sudo apt install flex bison`. @akissinger, please add this as dependencies at the `README`.

Now I am getting:

    src/gui/mainwindow.cpp:61:59: error: ‘resizeDocks’ was not declared in this scope
             resizeDocks({_stylePalette}, {130}, Qt::Horizontal);
                                                               ^
    make: *** [mainwindow.o] Error 1

The full log file is attached.
[log.txt](https://github.com/tikzit/tikzit/files/2489363/log.txt)

**Comment by hildogjr** [comment]
I am compiling by terminal, but have also tested by 'Qt Creater 4.7.1 (Based on Qt 5.11.2 GCC 5.3.1)' downloaded in http://download.qt.io/official_releases/qt/.

If I remove the line 61 there are other calls that have also to be removed.

In the Qt IDE I am having

    In file included from ../tikzit-master/src/gui/mainmenu.h:22:0,
                     from ../tikzit-master/src/gui/mainwindow.h:12,
                     from ../tikzit-master/src/gui/mainwindow.cpp:1:
    ../tikzit-master/ui_mainmenu.h:13:25: fatal error: QtGui/QAction: No such file or directory
    compilation terminated.
    Makefile:3526: recipe for target 'mainwindow.o' failed
    make: *** [mainwindow.o] Error 1
    19:33:19: The process "/usr/bin/make" exited with code 2.
    Error while building/deploying project tikzit (kit: Desktop Qt 5.11.2 GCC 64bit)
    When executing step "Make"

I tried this
https://stackoverflow.com/questions/8274514/qaction-no-such-file-or-directory
but nothing...

**Comment by hildogjr** [comment]
Should be interesting also, after fix / understand this issue, submit the package to official Ubuntu repository.

**Comment by akissinger** [comment]
I'm not sure what you mean by "The Linux portable binary is empty."

I just downloaded the tar.gz and followed the instructions on the website exactly and it works.

Currently, you need to be running at least Qt 5.10 to build from source, but I'm working on getting it to run as far back as 5.6 (part if issue #28). Ubuntu 18.04 ships with 5.9, so you need to install a newer version from the Qt site to get it working.

I'll add instructions about flex/bison. I left these out because they are a typical part of a "development" setup on most distros (though may not be installed by default).
