### ISSUE TITLE
If the PREFIX is assigned on qmake invocation, but not as an environment variable, it is ignored

### ISSUE THREAD

**Issue by gspr** [tikzit/tikzit#35]
Debian's automatic tools typically invoce qmake with something like `qmake PREFIX=/usr`, instead of setting `PREFIX` as an environment variable. In these cases, the current TikZiT project file seems to ignore `PREFIX` and re-set it to `/usr/local`. It would be nice if also assignments à la `qmake PREFIX=/usr` were honored.

**Comment by iblech** [comment]
It's [the same](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/libraries/qt-5/hooks/qmake-hook.sh) with NixOS. It's no big deal, we can certainly deal with this way of passing the prefix information, but it'd be slightly nicer if we could just use the standard way.

In case you want to change this behaviour, have a look at pull request #36. The fix is exceedingly simple.

**Comment by iblech** [comment]
Yes, we noticed, and asked for the final NixOS build to be merged in the NixOS repository. Thank you for your work in putting together the release! :-)

**Comment by gspr** [comment]
> FYI: This and the other minor issues have all been fixed, and I've just released 2.0.

Great. The 2.0 Debian package is now in unstable.
