### ISSUE TITLE
Importing a tikz graph

### ISSUE THREAD

**Issue by janbianchi** [tikzit/tikzit#61]
I wanted to include the following tikz graph. I opened the editor with CTRL+J, pasted it into the editor and parsed it with CTRL+T. Nothing happened!

Is my approach incorrect or is the tikz source simply too complicated?

\pgfmathsetmacro\nodedistance{3.3611111111111107}
\pgfmathsetmacro\nodewidth{width("konfession") + 0.2cm}
\pgfmathsetmacro\nodeheight{height("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ") + 0.4cm}
\pgfmathsetmacro\nodewidthCM{\nodewidth / 1cm}
\pgfmathsetmacro\scalefactor{0.6 * (\nodedistance / \nodewidthCM}

\tikzset{
manifest/.style={scale=\scalefactor,rectangle,draw,inner sep=0pt,minimum width=\nodewidth,minimum height=\nodeheight},
interaction/.style={scale=\scalefactor,circle,draw,radius={\nodewidth / 20},fill=black},
paths/.style={->,shorten >=1ex, shorten <=1ex, semithick, >=latex},
topaths/.style={->,shorten >=1ex, shorten <=1ex, dash dot, semithick, >=latex},
frompaths/.style={shorten >=1ex, shorten <=1ex, dotted, semithick, >=latex}
}

\begin{center}
\begin{tikzpicture}
\node [manifest] (VAR0) at (0* \nodedistance, 0) {alter};
\node [manifest] (VAR1) at (1* \nodedistance, 0) {konfession};
\node [manifest] (VAR2) at (2* \nodedistance, 0) {partei};
\node [manifest] (VAR3) at (3* \nodedistance, 0) {waehler};
\pgfmathsetmacro\startangle{-10.0}
\pgfmathsetmacro\deltaangle{20.0}
\pgfmathsetmacro\arc{\startangle + \deltaangle * 2}
\coordinate (start_dir) at ($(1 * \nodedistance, 0) + (\arc :0.66 * \nodedistance)$);
\coordinate (end_dir) at ($(3 * \nodedistance, 0) + (180 - \arc :0.66 * \nodedistance)$);
\draw [paths] (VAR1.{\arc}) .. controls (start_dir) and (end_dir) .. (VAR3.{(180 - \arc )});
\draw[paths] (VAR1.east) to node {} (VAR2.west);
\pgfmathsetmacro\arc{-\startangle - \deltaangle * 3}
\coordinate (start_dir) at ($(0 * \nodedistance, 0) + (\arc :0.99 * \nodedistance)$);
\coordinate (end_dir) at ($(3 * \nodedistance, 0) + (180 - \arc :0.99 * \nodedistance)$);
\draw [paths] (VAR0.{\arc}) .. controls (start_dir) and (end_dir) .. (VAR3.{(180 - \arc )});
\draw[paths] (VAR0.east) to node {} (VAR1.west);
\draw[paths] (VAR2.east) to node {} (VAR3.west);
\node [interaction] (IACT0) at (1.5 * \nodedistance, 1.787630388891315* \nodedistance) {};
\draw [topaths] (IACT0) to node {} (VAR3.north);
\draw [frompaths] (IACT0) to node {} (VAR1.north);
\draw [frompaths] (IACT0) to node {} (VAR0.north);
\end{tikzpicture}
\end{center}

**Comment by deepchatterjeeligo** [comment]
I was also having a similar problem. Could someone please point to how to import source code?

For example I have a simple `figure.tikz` with the content (which works inside a figure environment in latex)
```
\begin{tikzpicture}
	\draw[fill=gray!5] (-8, 4) rectangle (8,8);
\end{tikzpicture}
```

If I try to open this with tikzit, I don't see anything rendered. Also there is a "Cannot read tikz source" at the bottom left of the screen. something like:
![image](https://user-images.githubusercontent.com/23223278/101986822-f37eeb00-3c55-11eb-9827-19e593b6727f.png)

The use case I was thinking is to load an already existing source code and modify using tikzit.

**Comment by 0xACE** [comment]
I haven't read the tikz source in a while, but im guessing `tikzit`'s parser is failing to recognize that line.

The parser `tikzit` uses supports a very limited subset of actual `tikz` syntax. You will have to stick to the basic things `tikzit` does and then apply your advanced things afterwards...

Otherwise recently `paths` were added to tikzit, where you can correctly render polygons in any shape you like...

**Comment by deepchatterjeeligo** [comment]
Thank you. Is there any documentation related to what format the parser follows? This was just an example. I had a slightly involved figure, which I wanted to make further additions to using tikzit.

And I'm showing my ignorance here since I have never used tikzit. Do you have a suggestion of importing a figure that I already have in tikz? Or is it just that you need to start from scratch.
For now I have ploughed my way through editing source tikz, but it maybe useful to know for future figures.

**Comment by 0xACE** [comment]
Anytime bro.

> And I'm showing my ignorance here since I have never used tikzit. Do you have a suggestion of importing a figure that I already have in tikz? Or is it just that you need to start from scratch.

What kind of figure did you have in mind?

I can be available on gitter.im for "direct" guidance if you like, though I'm supposed to be available during European daytime hours. I'm online right now to catch up on all notifications I've missed the past few weeks.

Personally I just find it easier to just create the diagram in `tikzit` and rarely have to edit them manually...

>Thank you. Is there any documentation related to what format the parser follows?

Been sometime since i tinkered with `tikzit` but iirc the parser is very limited, I think you are esentially limited to

`\node [properties] (refstring) at (x,y) {Text goes here};`

And I'm just guessing it based on this line:

https://github.com/tikzit/tikzit/blob/300267089b80785551c4721684280efe654ec834/src/data/tikzparser.y#L192


> This was just an example. I had a slightly involved figure, which I wanted to make further additions to using tikzit.

Well I too draw important and complicated work ;)

![its important work](https://user-images.githubusercontent.com/1482942/90487594-33abe200-e12a-11ea-9dfc-1489f8f7665b.png)

Depends on what you need...

**Comment by deepchatterjeeligo** [comment]
Thanks for the advice. Just pinged you on gitter. BTW, the little explosion thing in the figure is really cool. If creating a gif how to do that is not much work, that would be helpful too.

**Comment by me7pako** [comment]
> 

Hey there, are you still available on gitter.im ?

**Comment by 0xACE** [comment]
Yes I am available. but I no longer own a device that provides graphical environment, so my help is limited.

What are you trying to accomplish?

**Comment by me7pako** [comment]
I can explain on gitter if you are still available there, basically I would like to use the software correctly. Your input can be greatly appreciated.

**Comment by me7pako** [comment]
> Yes I am available. but I no longer own a device that provides graphical environment, so my help is limited.
> 
> What are you trying to accomplish?

like this is the issue I created here : https://github.com/tikzit/tikzit/issues/146

**Comment by akissinger** [comment]
Hi all, sorry I haven't been following the tikzit issue tracker for a while. Thanks @0xACE for answering lots of Qs!

Tikzit indeed only parses a subset of legal tikz. The grammar it recognises is at the bottom of the docs here: https://tikzit.github.io/

If you want unusual stuff, you can get quite some mileage using path actions in your .tikzstyles:

https://tikz.dev/tikz-actions#tikz/preaction

...or defining custom nodes in your .tikzdefs. An example is in the tikzit "quantum" template:

https://github.com/tikzit/template-quantum/blob/master/quantum.tikzdefs
