### ISSUE TITLE
Closing the preview window also closes the entire program

### ISSUE THREAD

**Issue by 326623** [tikzit/tikzit#98]
I am using this application on Mac.

# Issue description
When I finish viewing the preview window, with a force of habit, I press Command+W to try to close the preview window, which also closes the main window. This behaviour is a bit surpising for me, as the focus is on the preview window, I expect it to only close the preview window.

I think it is better to only close the preview window rather than exiting the entire application after issuing a Command+W with the focus on preview window on Mac. Current workaround is to use Esc, but sometimes, I still press Command+W and get frustrated as the program exits :(

# Not so relevant to this issue, feel free to ignore
In addition, I wonder if it is possible to design the program such that we see the preview on the editing pane rather than having to resort to an additional preview window. I understand this is a much harder challenge. But with the current design, I have to constantly look back and forth the preview window and the editing pane to adjust the spacing of my drawing. I think what I want is to have something more like [TeXmacs](http://www.texmacs.org/tmweb/home/welcome.en.html).

**Comment by 0xACE** [comment]
# Command-W
I can't replicate the `Control-W` issue in `personal`, `master` nor `aur`. Which version of the program are you using?

As far as I can tell `tikzit` isn't triggering on `Command+W`. So I'm wondering what does `Command+W` do on mac? Because it soundslike it's not just "closing" 1 window. I guess this can be fixed but tbh I'm busy this week.

For future reference: PreviewWindow is a QDialog: https://doc.qt.io/qt-5/qdialog.html
 "A dialog window is a top-level window mostly used for short-term tasks and brief communications with the user."

# Editing pane
I think it could be easy to implement, but it has been a while since I worked on this project and I don't know how to go about this entire thing. Also I would argue a pane would be a bad idea: The preview window should be used for previewing, as a seperate window you can scale it for that exact purpose. If it were a pane it would most likely have a bad aspect ratio unless you suffer or happen to make a figure in that aspect ratio...

**Comment by 326623** [comment]
# Command-W
Quote from [Apple Document](https://support.apple.com/en-us/HT201236):

> Command-W: Close the front window. To close all windows of the app, press Option-Command-W.

Yes, I think the fix should be rather simple. When I am free, I can take a look in the source code and try to come up with a fix.

# Editing pane
Sorry. My writing above is not clear enough.

By editing pane, I mean to combine the editing grid and the preview window to achieve [WYSIWYG](https://en.wikipedia.org/wiki/WYSIWYG), which is hard to design and implement. The current editing gird only renders the skeleton of the drawing, which does not reflect its actual size and shape. To view the actual drawing, we need to invoke pdflatex to render it, which means if the node is too big that it collides with other nodes or lines, we cannot directly see that from the editing grid along. This causes me to look back and forth (now the **Command+W** frustrates me) to adjust the distance for each node.

Still, this method is much better than writing latex markup in Tikz :) Hats off to the authors for this app.

**Comment by 0xACE** [comment]
# Command-W
> Yes, I think the fix should be rather simple. When I am free, I can take a look in the source code and try to come up with a fix.

Great!

# Editing pane
I see, I understand what you mean. Well I have been working on this in #82 

Example of my `personal` rendering vs `master`:

![82](https://user-images.githubusercontent.com/1482942/82743624-77769180-9d5d-11ea-94be-218cf270413a.png)

Unfortunately since i had that discussion my branch went even further away from `master`... And I've been tinkering with `inkscape` lately

![side-projects-vs-unfinished-ol3jikdym2251](https://user-images.githubusercontent.com/1482942/97385167-0ec1b100-18c9-11eb-8bf9-e6cf3c888b65.jpg)


 but I frequently fallback to `tikzit` because it launches so fast and it enforces me to keep a clean and aesthetic unlike inkscape...

**Comment by 326623** [comment]
Hi, I think I manage to make a simple fix. How would the normal procedure be to get this merged?
